### ISSUE TITLE
/usr/lib/libcrypto.35.dylib code signature not valid

### ISSUE THREAD

**Issue by dnlshllrd24RTY** [tihmstar/futurerestore#72] opened 2017-03-02 13:37 UTC
Hi,

I have been getting the following error

```
F-MBP:iPhone $ ./futurerestore_osx
dyld: Library not loaded: /usr/lib/libcrypto.35.dylib
  Referenced from: /Users//Desktop/iPhone/./futurerestore_osx
  Reason: no suitable image found.  Did find:
	/usr/lib/libcrypto.35.dylib: code signature invalid for '/usr/lib/libcrypto.35.dylib'

	/usr/lib/libcrypto.35.dylib: code signature invalid for '/usr/lib/libcrypto.35.dylib'

Trace/BPT trap: 5
```

Can anyone shed any light?

**Comment by Kagemasuru** [comment] 2017-03-02 17:12
dear dnlshllrd24RTY:

i had the same issue and got a beard for the solution-searching.
at least it wasnt a big piece of an challenge.
i just had to download the most current futurerestore version (sth like the very beginning of ferbruary) and it worked ( must do chmod +x for sure)

also you need homebrew, xcode and openssl

**Comment by tihmstar** [comment] 2017-03-27 06:59
This was caused by the buildsystem i was using.
I changed a few things. Now linking openssl and libzip statically.
Should be fixed in the latest build

**Closed by tihmstar** 2017-03-27 06:59 UTC
