### ISSUE TITLE
Segfault 11 on APTicket verification

### ISSUE THREAD

**Issue by snxraven** [tihmstar/futurerestore#85] opened 2017-03-23 12:03 UTC
BasebandCertId: 3840149528
ProductType: iPhone7,1

https://ghostbin.com/paste/dkpem

Using the latest update.

**Comment by boobang** [comment] 2017-03-23 12:45
same problem

**Comment by tihmstar** [comment] 2017-03-25 11:11
Can you try with version 93?
Also if that doesn't fix the segfault, can you verify your shsh files using img4tool_v90 and check whether that crashes?

**Comment by snxraven** [comment] 2017-03-25 15:19
FutureRestore Crash as above.

Log from img4tool_v90
C:\Users\snxra>E:\Desktop\img4tool_windows.exe -v BuildManifest.plist -s 2859925716208602023_iPhone7,1_10.2-14C92.shsh2
Version: 438cbe966817b766afd6373affc5cb0aef4ff4f3 - 90
[Error] reading file failed 2859925716208602023_iPhone7,1_10.2-14C92.shsh2

**Comment by tihmstar** [comment] 2017-03-25 15:28
can you email that file to me please?

**Comment by boobang** [comment] 2017-03-25 15:54
The problem still occurs... Segfault 11.. I've checked every single shsh files on TSSServer1conan.. My shsh files which are valid.. https://tsssaver.1conan.com/shsh/1980853534615154/

**Comment by quent176** [comment] 2017-03-25 17:03
Same for me, doesn't work. (iphone 6; 8.3 JB)
https://ghostbin.com/paste/6cwuj

I used the latest version of FutureRestore and shsh files are valid.

**Comment by snxraven** [comment] 2017-03-25 18:44
Here you go tihmstar
 http://jbbar.ml/rgenius/shsh/2859925716208602023_iPhone7,1_10.2-14C92.shsh2

**Comment by tihmstar** [comment] 2017-03-26 08:32
So i checked the file. Seems to be valid: https://ghostbin.com/paste/mckyy
I just tested restoring my i5s with the release version of futurerestore and i also get a segfault. however it works fine if i compile it locally. Can you maybe check if it works if you compile from source? I think this might be related to my buildsystem

**Comment by snxraven** [comment] 2017-03-26 09:18
I am having issues getting a working build system too....i will keep trying i guess

**Comment by snxraven** [comment] 2017-03-26 09:41
./configure: line 3014: syntax error near unexpected token `libplist,'
./configure: line 3014: `PKG_CHECK_MODULES(libplist, libplist >= 1.12)'
Ravens-iMac:futurerestore-master raven$ sudo port install pkg-config

**Comment by boobang** [comment] 2017-03-26 10:42
the link (api.tihmstar.net/builds/futurerestore/futurerestore-latest.zip) only download the version 93, not 94. Please fix @tihmstar. Thank you very much!

**Comment by snxraven** [comment] 2017-03-26 10:52
@tihmstar I compiled on a fresh Ubuntu install

Here is the log: https://ghostbin.com/paste/e65fb this is R94

**Comment by snxraven** [comment] 2017-03-26 10:58
raven@raven-desktop:~/Desktop/re$ sudo img4tool -v BuildManifest.plist -s 2859925716208602023_iPhone7,1_10.2-14C92.shsh2
Version: 481d959a5e36f22aa0b2bcb58914ab84b8107f4d - 94
Version: 0
MANB
MANP: MANP: ------------------------------
BNCH: BNCH: 75e2a9f957ba16d81b9eef931a535cd3998c81fd
BORD: BORD: 4
CEPO: CEPO: 1
CHIP: CHIP: 28672
CPRO: CPRO: true
CSEC: CSEC: true
ECID: ECID: 2859925716208602023
SDOM: SDOM: 1
snon: snon: 2710a4b0252b59c29feebdcb24bd77663427aabc
srvn: srvn: ed943a4ae3d9688ef10838855f380f901eec7b83

[OK] IM4M signature is verified by TssAuthority
[Error] im4m_buildidentity_check_cb: can't find any identity which matches all hashes inside IM4M
[Error] getBuildIdentityForIM4M: found buildidentiy, but can't read information
[Error] verifyIMG4: IM4M is

**Comment by boobang** [comment] 2017-03-26 11:00
@snxraven can you please send me the futurerestore file ?

**Comment by snxraven** [comment] 2017-03-26 11:06
I only have it for linux on local not sure how to do that

**Comment by snxraven** [comment] 2017-03-26 11:08
1Conans checker reports valid:
https://ghostbin.com/paste/3c694

**Comment by boobang** [comment] 2017-03-26 13:54
@tihmstar : same with @snxraven, still being stucked on restore logo when trying to downgrade from iOS 10.3b1 to 10.2.0 using the lastest futurerestore (v94)
```
Version: 481d959a5e36f22aa0b2bcb58914ab84b8107f4d - 94
futurerestore init done
reading ticket 1980853534615154_iPhone62_n53ap_10.2-14C92.shsh done
reading ticket 2.shsh done
reading ticket 3.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is F2
waiting for nonce: 9e 4c 51 80 09 d0 0d f1 90 a4 50 b3 b4 76 91 76 88 12 36 0c 
waiting for nonce: 9f 4a ee c7 26 e7 c6 82 33 9d db 3c 6c 2d ec 52 66 2d c5 17 
waiting for nonce: 98 04 d9 9e 85 bb af d4 bb 11 35 a1 04 47 73 b4 df 9f 1b a3 
Got ApNonce from device: 08 cc b3 55 92 f1 d3 87 fe d0 87 ef 50 24 07 eb ac 5f d0 3e 
Got ApNonce from device: a3 eb 70 cc b7 f4 00 5d 27 89 60 4f 77 24 c6 f3 7b 4d f0 96 
Got ApNonce from device: 6c 16 ed 05 07 25 95 70 04 0a db 36 12 9a e2 c9 13 20 c9 9d 
Got ApNonce from device: 7b 29 a3 b0 5a 6c f0 31 33 69 c0 a5 91 11 e8 82 3c 6f 6c f1 
Got ApNonce from device: 9e 4c 51 80 09 d0 0d f1 90 a4 50 b3 b4 76 91 76 88 12 36 0c 
Device has requested ApNonce now
Found device in Recovery mode
Identified device as n53ap, iPhone6,2
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from 'iPhone_4.0_64bit_10.2_14C92_Restore/058-54548-094.dmg'
Extracting iBEC.n53.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (627864 bytes)...
waiting for device to reconnect... 
Getting SepNonce in recovery mode... 87 17 db 23 49 6c 2c a9 3f d1 80 21 14 a9 d4 d1 4c 7d 30 c1 
Getting ApNonce in recovery mode... 9e 4c 51 80 09 d0 0d f1 90 a4 50 b3 b4 76 91 76 88 12 36 0c 
Recovery Mode Environment:
iBoot build-version=iBoot-3406.50.223
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~iphone.s5l8960x.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (11640 bytes)...
ramdisk-size=0x10000000
Extracting 058-54560-094.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (40326167 bytes)...
Extracting DeviceTree.n53ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (107953 bytes)...
Extracting kernelcache.release.n53...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (11952409 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Waiting for device...
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11
```

**Comment by tihmstar** [comment] 2017-03-26 14:08
So i think i fixed my buildsystem so the segfault issue should be resolved now. New builds will be pushed in a few hours.

about that "unable to open device in restore mode" issue that many people have, i'm kinda clueless tbh. If we rule out all thoses which have that issue because of VM, there still seems something which i have missed. 
So basically what is supposed to happen is: 
1) the device boots into recovery with the correct nonce
2) we send the iBEC of the iOS we want to downgrade to, stiched with our APTicket to the device and boot it.
3) make the screen green for 2 seconds (for debugging purposes) to see that iBEC booted successfully.
4) continue with the restore...

So since we do not see the green screen, this means that the device has not booted iBEC.
This means that it will ignore all the other components we send, stay in iBoot with the "attach to itunes logo" and will not boot into restore mode.

So the issue has to be somewhere at the point where we try to send iBEC.
A lot of things could be causing this but i ruled out a few of them:
- APTicket might be bad -> ruled out this one by validating signature and matching it with the buildmanifest
- trying to boot wrong iBEC -> don't think it's this, since idevicerestore handles this and i didn't change anything there. also it seems to work for normal restore
- implementation erros/timeouts/sleep times -> not sure about this one


Could you maybe try booting that ibec manually?
extract the correct iBEC from the ipsw you're trying to restore (which should be iBEC.n56.RELEASE.im4p according to your restore log @snxraven).
Then create a signed img4 with "img4tool -c ibec.img4 -p iBEC.n56.RELEASE.im4p -s 2859925716208602023_iPhone7,1_10.2-14C92.shsh2"
Now boot your device in recovery mode and make sure it has the correct nonce.
You can check the nonce either with igetnonce (http://api.tihmstar.net/builds/igetnonce/igetnonce-latest.zip) or with "irecovery -q".
If the device is in recovery mode and has the correct nonce that matches your APTicket upload the ibec with "irecovery -f ibec.img4" and then boot it "irecovery -c go".
Your screen should turn black.
To make sure you actually booted that ibec you can try setting the backgroundcolor either with
irecover -c "bgcolor 0 255 0" (note: you actually need the " because the bgcolor command has spaces)
or start the irecovrey shell with "irecovery -s" and then type bgcolor 0 255 0

So yea, i'd like to know whether you gusy can boot that ibec at all. Maybe you have any ideas?

**Comment by snxraven** [comment] 2017-03-26 17:13
@tihmstar I followed your guide to a tee, I can not boot iBEC, the commands run but the device just stays at the restore screen. I have tried both with and without sudo.

**Comment by tihmstar** [comment] 2017-03-26 17:49
@snxraven So looks like either something is wrong with the APTicket, the device has the wrong nonce or we're trying to boot the wrong iBEC. Are you sure igetnonce/irecovery -q shows the correct nonce? 
Also can you try booting the other ibecs with the procedure described above?
Also please verify the ibec.img4 you created with "img4tool -v BuildManifest.plist ibec.img4" (make sure to use the BuildManifest from the ipsw, not the one you pass to futurerestore for baseband/sep)

**Comment by snxraven** [comment] 2017-03-26 17:51
Let me verify

**Comment by snxraven** [comment] 2017-03-26 17:55
sudo img4tool -v BuildManifest.plist ibec.img4Version: 481d959a5e36f22aa0b2bcb58914ab84b8107f4d - 94
IMG4:
IM4P: ---------
type: ibec
desc: iBoot-3406.30.8
size: 0x00099000

KBAG
num: 1
22f3e259f813423b37e306c88140e55b
06ba988f98099e9c9ac39e4816673607053ced23b48ca0b427a67d099d9672cf
num: 2
f0db53f9af5711fc22599ec14c736c51
8a9997136c9269bd0d5abfc2476b7706eef3052791efa6fe29cea24d9d80fd25

IM4M: ---------
Version: 0
MANB
MANP: MANP: ------------------------------
BNCH: BNCH: 75e2a9f957ba16d81b9eef931a535cd3998c81fd
BORD: BORD: 4
CEPO: CEPO: 1
CHIP: CHIP: 28672
CPRO: CPRO: true
CSEC: CSEC: true
ECID: ECID: 2859925716208602023
SDOM: SDOM: 1
snon: snon: 2710a4b0252b59c29feebdcb24bd77663427aabc
srvn: srvn: ed943a4ae3d9688ef10838855f380f901eec7b83


[OK] IM4P is valid for the attached IM4M
[OK] IM4M signature is verified by TssAuthority
[OK] IM4M is valid for the given BuildManifest for the following restore:

BuildNumber : 14C92
BuildTrain : Corry
DeviceClass : n56ap
FDRSupport : YES
RestoreBehavior : Erase
Variant : Customer Erase Install (IPSW)
[IMG4TOOL] file is valid!

**Comment by tihmstar** [comment] 2017-03-26 18:16
Does the ECID match?

**Comment by snxraven** [comment] 2017-03-27 00:43
I saw you added ECID checking to the branch. Going to try now

**Comment by boobang** [comment] 2017-03-27 03:02
same :( no hope of downgrading from 10.3 beta 1 for me :( ..
```
Device has requested ApNonce now
Found device in Recovery mode
Identified device as n53ap, iPhone6,2
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Error] ECID inside APTicket does not match device ECID
APTicket is valid for    7099367486672 but device is      674f346f4d0
[Error] APTicket can't be used for restoring this device
Done: restoring failed.
Failed with errorcode=-45
Bangs-Mac-Pro:futurerestore bang$ 
```

**Comment by snxraven** [comment] 2017-03-28 00:35
@boobang I think you do have valid blobs from 1conan
Try this: https://beta.tsssaver.1conan.com/shsh/7099367486672/10.2/noapnonce/7099367486672_iPhone6,2_10.2-14C92.shsh2

https://beta.tsssaver.1conan.com/shsh/7099367486672/

**Comment by boobang** [comment] 2017-03-28 02:37
@snxraven: exactly what am I thinking.. The problem is not the futurerestore detect wrong SHSH blobs, that is that validator tool check the wrong SHSH ECID type, as I has tested on Tsssaver 1conan's server, I chose "Hex" type so it will show correct blobs and checked the link of the TSSSaver 1Conan's server gives, it only contains "Dec" type, so you can see my last comment contains "[Error] ECID in ApTicket does not match device ECID Apticket for ...",..The ECID which the @tihmstar's validator only checks "Dec" type but it detects wrongly in "Hex" type. "Dec" type doesn't contain any letter of words but numbers but the "Hex" type does so it returns to be failed to attempt your device to be restored. So can you re-open this issue? This maybe a new bug.. 
@tihmstar: you will need to see this. The recent issue in "Open" tab had the same issue with us..!

**Comment by 1Conan** [comment] 2017-03-28 05:05
@boobang 
Hex ECIDs are converted to decimal before getting inserted to the db and passed to tsschecker. 
I made it convert to decimal because of the issues with tsschecker before. (Hex ecids that are all numbers. tsschecker has a bug with that before.) I kept it like that since changing it would be quite troubling.

**Comment by boobang** [comment] 2017-03-28 05:08
@1Conan: you may need this... and this is my SHSH blobs saved in your server: https://beta.tsssaver.1conan.com/shsh/7099367486672/
This string is read as Dec "7099367486672" and this string is Hex "674f346f4d0". But @tihmstar's tool only detects wrong...
```
checking APTicket to be valid for this restore...
[Error] ECID inside APTicket does not match device ECID
APTicket is valid for    7099367486672 but device is      674f346f4d0
[Error] APTicket can't be used for restoring this device
```

**Comment by 1Conan** [comment] 2017-03-28 05:37
I believe this should be addressed by @tihmstar. tsschecker is supposed to accept both decimal and hexadecimal ECIDs.

**Comment by cliffw** [comment] 2017-03-28 07:24
Thanks, the new version of futurerestore_macos v 95 resolved this problem for me on my iPhone 6 upgrading from iOS 9.3.3 jailbroken.

**Comment by quent176** [comment] 2017-03-28 12:36
Also worked for me with 8.3 and V95 for MacOS.
No Segfault 11 (original issue) + no problem to go in recovery mode (other issue)

Thanks Boss !

**Comment by tihmstar** [comment] 2017-03-29 10:03
@boobang same as #87 
closing this issue now, since the original problem seems to be resolved

**Closed by tihmstar** 2017-03-29 10:03 UTC
