### ISSUE TITLE
libcrypto.35.dylib not loaded

### ISSUE THREAD

**Issue by alucard0134** [tihmstar/futurerestore#1] opened 2016-12-29 00:46 UTC
Probably just my own retardation but here goes:

Running on 10.10.1 I get the following error

```
$ ./futurerestore_osx 
dyld: Library not loaded: /usr/lib/libcrypto.35.dylib
  Referenced from: /Users/alucard/Desktop/s/./futurerestore_osx
  Reason: image not found
Trace/BPT trap: 5
```
Tried running brew install openssh, but that didn't do much. Yippee

**Comment by phparmand** [comment] 2016-12-29 04:56
you have to download the file and place it in that location. just do a google search for "libcrypto.35.dylib" and then do command shift G in finder and navigate to /usr/lib and paste it there

**Comment by alucard0134** [comment] 2016-12-29 06:37
don't know about you bud but i even scoured to the devils asshole looking for this file

**Comment by phparmand** [comment] 2016-12-29 08:26
here 
https://drive.google.com/open?id=0B3EWBh37FFuRdFg5ekNLZG1yS2s

**Comment by Bubertino** [comment] 2016-12-29 21:22
Have the same problem .. running OSX on VMware and for some reason couldn't copy the file to /usr/lib . Tried SU in terminal and and after entering my password it says Denied :/

**Comment by tihmstar** [comment] 2017-01-01 19:37
This problem was caused by the buildsystem i'm using to compile binaries.
This is not releated to the project itself.
Also it's been fixed now

**Closed by tihmstar** 2017-01-01 19:37 UTC
