### ISSUE TITLE
Segmentation fault when running futurerestore for iPad2,1

### ISSUE THREAD

**Issue by matteyeux** [tihmstar/futurerestore#96] opened 2017-04-02 13:00 UTC
Segmentation fault when running futurerestore for iPad2,1
I'm running it on Ubuntu 16.04
Here is the output : 
```
$ sudo ./futurerestore/futurerestore -t iPad2,1-9.3.4.shsh --no-baseband iPad2,1_9.3.4_13G35_Restore.ipsw
Version: d8b69365ecb78414d8a6bf024d449133f581b6d4 - 106
[INFO] 32bit device detected
futurerestore init done
reading ticket iPad2,1-9.3.4.shsh done
INFO: device serial number is XXXXXXXXXX

WARNING: user specified not to flash a baseband. This can make the restore fail if the device needs a baseband!
if you added this flag by mistake you can press CTRL-C now to cancel
continuing restore in 5 4 3 2 1
Found device in Recovery mode
Device already in Recovery mode
Found device in Recovery mode
Identified device as k93ap, iPad2,1
Segmentation fault (core dumped)
```

**Comment by albyvar** [comment] 2017-04-02 13:07
With what have you saved shsh?

**Comment by matteyeux** [comment] 2017-04-02 13:09
Savethemblobs had no issue with alitek's stuff

**Comment by tihmstar** [comment] 2017-04-02 16:05
Can you email those shsh files to me?

**Comment by aofathy** [comment] 2017-04-03 02:05
I've the exact same issue while trying with iPad3,1 and 6.1.3 shsh on Ubuntu 16.04 when I decided to give it a try after being stuck with "Waiting for device" on Mac which is reported on #95

**Comment by tihmstar** [comment] 2017-04-03 10:19
can you check whether the issue is fixed with version 111?

**Comment by aofathy** [comment] 2017-04-03 14:56
@tihmstar still throws that segmentation fault with v114 on Ubuntu 16.04 too.

**Comment by Noah-p0werd0wn** [comment] 2017-04-04 23:04
I also have the problem with iPhone5,4

**Closed** 2021-03-20 19:10 UTC
